name: Mirroring armv7 Contaminated Debian Packages

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/armv7-contamination-deb-mirror.yml"
  pull_request:
    branches:
      - master

env:
  QT5_DEB_VERSION: "5.15.2+dfsg"
  QT5_DEB_REV_VERSION: "3"
  DEB_ARCH: "armhf"
  PACKAGECLOUD_REPO: "experimental"
  OS: "debian"
  DISTRO: "bullseye"
  POOL_URL: "http://deb.debian.org/debian/pool/main/q/qtwebengine-opensource-src"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "libqt5webengine5"
            type: "deb"

          - package: "libqt5webenginecore5"
            type: "deb"

          - package: "libqt5webenginewidgets5"
            type: "deb"

          - package: "qml-module-qtwebengine"
            type: "deb"

          - package: "qtwebengine-opensource-src"
            type: "dsc"

    steps:
      - if: matrix.type == 'deb'
        run: wget ${{ env.POOL_URL }}/${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}-${{ env.QT5_DEB_REV_VERSION }}_${{ env.DEB_ARCH }}.deb

      - if: matrix.type == 'dsc'
        # Download additional source files for source package release
        run: |
          wget ${{ env.POOL_URL }}/${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}-${{ env.QT5_DEB_REV_VERSION }}.dsc
          wget ${{ env.POOL_URL }}/${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}-${{ env.QT5_DEB_REV_VERSION }}.debian.tar.xz
          wget ${{ env.POOL_URL }}/${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}.orig.tar.xz

      - uses: pi-top/ghaction-packagecloud@main
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
          files: ./*.${{ matrix.type }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
