name: Mirroring armv7 Contaminated Debian Packages

on: workflow_dispatch

env:
  QT5_DEB_VERSION: "5.15.2+dfsg-3"
  DEB_ARCH: "armhf"
  PACKAGECLOUD_REPO: "experimental"
  OS: "debian"
  DISTRO: "bullseye"
  POOL_URL: "http://deb.debian.org/debian/pool/main/q/qtwebengine-opensource-src"

jobs:
  build-debian-package:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "libqt5webengine5"
            type: "deb"

          - package: "libqt5webenginecore5"
            type: "deb"

          - package: "libqt5webenginewidgets5"
            type: "deb"

          - package: "qml-module-qtwebengine"
            type: "deb"

          - package: "qtwebengine-opensource-src"
            type: "dsc"

    steps:
      - if: matrix.type == 'deb'
        run: echo "FILENAME=${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}_${{ env.DEB_ARCH }}.deb" >> $GITHUB_ENV

      - if: matrix.type == 'dsc'
        run: echo "FILENAME=${{ matrix.package }}_${{ env.QT5_DEB_VERSION }}.dsc" >> $GITHUB_ENV

      - run: wget ${{ env.POOL_URL }}/${{ env.FILENAME }}

      - uses: docker://lpenz/ghaction-packagecloud:v0.3
        with:
          repository: ${{ env.PACKAGECLOUD_REPO }}/${{ env.OS }}/${{ env.DISTRO }}
          files: ./${{ env.FILENAME }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
